apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsrsd-vocprez-deployment
  labels:
    app: gsrsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsrsd
  template:
    metadata:
      labels:
        app: gsrsd
    spec:
      containers:
      - name: gsrsd-vocprez
        image: 680471986828.dkr.ecr.ap-southeast-2.amazonaws.com/gsrsd/vocprez:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gsrsd-vocprez-service
spec:
  selector:
    app: gsrsd
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gsrsd-vocprez-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
spec:
  rules:
    - host: gsrsd.surroundaustralia.com
      http:
        paths:
          - backend:
              serviceName: gsrsd-vocprez-service
              servicePort: 80
